const responses = {
    "Hola buenas tardes":"!Hola gracias por ponerte en contacto con nosotros. Recibimos tu mensaje y agradecemos tu interés",
    "Hola":"!Hola gracias por ponerte en contacto con nosotros. Recibimos tu mensaje y agradecemos tu interés",
    "qué es el comité de ingeniería de sistemas": "El comité de ingeniería de sistemas es un grupo de estudiantes y profesores que se encarga de implementar mejoras para el desarrollo de la carrera, organizar eventos académicos y apoyar a los estudiantes en su formación profesional.",
    "qué eventos organiza el comité": "El comité organiza una variedad de eventos, incluyendo conferencias, talleres, hackathons, y ferias de empleo. Estos eventos están diseñados para complementar la formación académica y brindar oportunidades de networking y desarrollo profesional.",
    "cómo puedo solicitar una asesoría académica": "Puedes solicitar una asesoría académica enviando un correo electrónico a comite_asesorias@ejemplo.com con tu nombre, número de estudiante y el tema en el que necesitas ayuda. También puedes asistir a nuestras sesiones de asesoría en los horarios establecidos.",
    "cómo puedo participar en proyectos o prácticas profesionales": "Para participar en proyectos o prácticas profesionales, debes estar atento a las convocatorias que publicamos en nuestro sitio web y en las redes sociales. También puedes acercarte a las reuniones del comité para obtener más información.",
    "cuál es el horario de atención del comité": "El horario de atención del comité es de lunes a viernes de 10:00 AM a 4:00 PM. Puedes visitarnos en nuestra oficina ubicada en el edificio de ingeniería, sala 203.",
    "cómo puedo contactar al comité": "Puedes contactar al comité a través del correo electrónico comite_contacto@ejemplo.com o llamando al número (123) 456-7890. También estamos disponibles en nuestras redes sociales.",
    "dónde puedo encontrar recursos académicos y materiales de estudio": "Puedes encontrar recursos académicos y materiales de estudio en la sección de recursos de nuestro sitio web. Además, el comité organiza sesiones de intercambio de materiales donde puedes obtener y compartir recursos con otros estudiantes.",
    "cuándo son las reuniones del comité y cómo puedo asistir": "Las reuniones del comité se realizan todos los jueves a las 3:00 PM en la sala de conferencias del edificio de ingeniería. Todos los estudiantes están invitados a asistir y participar en la planificación y ejecución de las actividades del comité.",
    "cómo puedo reportar una mejora que se pueda implementar en la carrera": "Puedes reportar mejoras enviando un correo electrónico a comite_mejoras@ejemplo.com con una descripción detallada de tu propuesta. También puedes asistir a las reuniones del comité para presentar tus ideas en persona.",
    "cómo puedo participar en un evento organizado por el comité": "Para participar en un evento organizado por el comité, debes inscribirte a través de nuestro sitio web en la sección de eventos. También puedes seguir nuestras redes sociales para estar al tanto de las convocatorias y fechas de inscripción.",
    "cuáles son las fechas de inscripción para la universidad": "Las fechas de inscripción varían cada semestre. Te recomendamos visitar el sitio web oficial de la universidad en la sección de admisiones o contactar a la oficina de admisiones al correo admisiones@universidad.com para obtener la información más actualizada.",
    "cuándo son los exámenes de segunda oportunidad": "Los exámenes de segunda oportunidad suelen programarse al final del semestre. Puedes consultar el calendario académico en el sitio web de la universidad o contactar a la coordinación académica para más detalles.",
    "cómo puedo solicitar una fecha para un examen o evento": "Para solicitar una fecha para un examen o evento, debes enviar una solicitud formal a la coordinación académica. Puedes hacerlo a través de su correo electrónico o asistiendo a su oficina durante el horario de atención.",
    "cuándo es el día del examen de ingreso": "El día del examen de ingreso se anuncia en el sitio web de la universidad en la sección de admisiones. Asegúrate de revisar esta información y de inscribirte a tiempo para el examen.",
    // Añade más preguntas y respuestas según sea necesario
};

module.exports = responses;
